src/Entity/Marque.php
<?php

namespace App\Entity;

use App\Repository\MarqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MarqueRepository::class)
 */
class Marque
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="marque", orphanRemoval=true)
     */
    private $Produits;

    public function __construct()
    {
        $this->Produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->Produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->Produits->contains($produit)) {
            $this->Produits[] = $produit;
            $produit->setMarque($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->Produits->contains($produit)) {
            $this->Produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getMarque() === $this) {
                $produit->setMarque(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{

    Const COULEUR=[
        1=>'Blanc',
        2=>'Noir',
        3=>'Rose',
        4=>'Bleu',
        5=>'Vert',
        6=>'Jaune',
        7=>'Marron',
        8=>'Viollet',
        9=>'Rouge',
        10=>'Cyan',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var
     * @ORM\Column (type="string",length=248,unique=true,nullable=true)
     * @Gedmo\Slug (fields={"Titre","DateCreation"},updatable=false,dateFormat="d/m/y")
     */
    private $slug;

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="float")
     */
    private $prixTTC;

    /**
     * @ORM\Column(type="float")
     * @Assert\Regex("/^[0-9]{2,}[.]?[0-9]*$/")
     */
    private $Poids;

    /**
     * @ORM\Column(type="integer")
     */
    private $Couleur;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateCreation;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min="3",max="100")
     */
    private $StockQte;

    /**
     * @ORM\Column(type="boolean",options={"default":false})
     */
    private $Actif;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="Produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $marque;

    /**
     * @ORM\ManyToOne(targetEntity=Stock::class, inversedBy="relation")
     */
    private $stock;

    public function __construct()
    {
        $this->Actif=false;
        $this->setDateCreation(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrixTTC(): ?float
    {
        return $this->prixTTC;
    }

    public function setPrixTTC(float $prixTTC): self
    {
        $this->prixTTC = $prixTTC;

        return $this;
    }

    public function getPoids(): ?float
    {
        return $this->Poids;
    }

    public function setPoids(float $Poids): self
    {
        $this->Poids = $Poids;

        return $this;
    }

    public function getCouleur(): ?int
    {
        return $this->Couleur;
    }

    public function setCouleur(int $Couleur): self
    {
        $this->Couleur = $Couleur;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getStockQte(): ?int
    {
        return $this->StockQte;
    }

    public function setStockQte(int $StockQte): self
    {
        $this->StockQte = $StockQte;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->Actif;
    }

    public function setActif(bool $Actif): self
    {
        $this->Actif = $Actif;

        return $this;
    }

    public function getCouleurType()
    {
        return self::COULEUR[$this->getCouleur()];
    }

    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

}

templates/template/_formProduit.html.twig
{% if formType == 'edit' %}
    {{ form_start(form ,{'method' : 'post','name' : 'produitEdit'}) }}
{% else %}
    {{ form_start(form ,{'method' : 'post','name' : 'produitAdd'}) }}
{% endif %}
    {{ form_errors(form) }}
<div class="row">
    <div class="col-md-4">
        {{ form_label(form.Titre) }}
        {{ form_widget(form.Titre) }}
        {{ form_errors(form.Titre) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.Description) }}
        {{ form_widget(form.Description) }}
        {{ form_errors(form.Description) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.prixTTC) }}
        {{ form_widget(form.prixTTC) }}
        {{ form_errors(form.prixTTC) }}
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        {{ form_label(form.Poids) }}
        {{ form_widget(form.Poids) }}
        {{ form_errors(form.Poids) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.Couleur) }}
        {{ form_widget(form.Couleur) }}
        {{ form_errors(form.Couleur) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.Stock) }}
        {{ form_widget(form.Stock) }}
        {{ form_errors(form.Stock) }}
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        {{ form_label(form.Actif) }}
        {{ form_widget(form.Actif) }}
        {{ form_errors(form.Actif) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.DateCreation) }}
        {{ form_widget(form.DateCreation) }}
        {{ form_errors(form.DateCreation) }}
    </div>
    <div class="col-md-4">
        {{ form_label(form.marque) }}
        {{ form_widget(form.marque) }}
        {{ form_errors(form.marque) }}
    </div>
</div>
{{ form_rest(form) }}
<button class="btn btn-primary">Valider</button>
{{ form_end(form) }}

templates/template/_showProduit.html.twig
<div class="container">
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <h1>{{ produit.titre }}</h1>
                    <h2>{{ produit.stockQte }} pièces - {{ produit.poids }} Kg</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ produit.prixTTC | number_format(0,'',' ') }} €</div>
                    <a href={{path('client_produit_contact',{'slug':produit.slug})}} class="btn btn-primary">Contactez nous</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ produit.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Stock</td>
                        <td>{{ produit.stockQte }}</td>
                    </tr>
                    <tr>
                        <td>Poids</td>
                        <td>{{ produit.poids }} Kg</td>
                    </tr>
                    <tr>
                        <td>Couleur</td>
                        <td>{{ produit.couleurType }}</td>
                    </tr>
                    <tr>
                        <td>Marque</td>
                        <td>{{ produit.marque.nom }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>
</div>